version: '3.7'

services:
  rest:
    container_name: flask
    build: ./services/rest
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/rest:/usr/src/app
    env_file:
      - ./.env.dev
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
